### ISSUE TITLE
Colors in config

### ISSUE THREAD

**Issue by AmiroEmad** [MCrafterss/ServerManager#3]
hello guys if you please tell me how to make config have colors with &

that will be something that helps me alot in my code style

( i know php and i know what is str_replace but i dont know how to use str_replace to make it do this in config in my plugin )

**Comment by remotevase** [comment]
This is the gist of ir":
You gotta detect in config if there are any "&" symbols. 
If there are, use the str_replace to replace the & with a section sign. 

I think you could do it that way. Also look at ldx's MOTD plugin for the actual code

**Comment by AmiroEmad** [comment]
Finally I figured it up what about setting the string on str_replace to cfg get all that might do it @remote_vase thx

**Comment by remotevase** [comment]
ah, kk
Also, you mentioned me wrong. GH doesnt allow underscores so im not
@remote_vase but I am @remotevase XP

**Comment by AmiroEmad** [comment]
will that work
note : i know that the mcpe color mark isnt $ but i dont have it in my keyboard
 <?php
$string = $cfg->getAll();
str_replace("$", "&", $string); 
?>

**Comment by remotevase** [comment]
It should ...

**Comment by Ad5001** [comment]
Nope @AmiroEmad ,
It should be :
str_replace("&", "§", $string);

If you want the syntaxe, here it is:
str_replace(search, replacement, where to replace);

**Comment by remotevase** [comment]
Oh, oops lol

**Comment by AmiroEmad** [comment]
@Ad5001 thx for the help

**Comment by AmiroEmad** [comment]
@remotevase another oops from me

**Comment by Survingo** [comment]
Well, ok
