### ISSUE TITLE
OMG AMIR!!! THE NAMESPACE

### ISSUE THREAD

**Issue by iPocket** [MCrafterss/ServerManager#5]
You should change it (and all the plugins) to **M**Crafters\\**Pluginname**!!!
@AmiroEmad

**Comment by AmiroEmad** [comment]
no no no dont do it thats outdated

**Comment by AmiroEmad** [comment]
come down thats not needed at all 

unless there is a sub directory of mcrafters 

if you see here you get in src and you find mcrafters and when you open you find source code directly adding another file is useless

**Comment by AmiroEmad** [comment]
tested and the plugin works with no errors so not needed + the plugin isn't done yet

**Comment by iPocket** [comment]
ah, a mistake, sorry.
