### ISSUE TITLE
Help Please 

### ISSUE THREAD

**Issue by AmiroEmad** [MCrafterss/ServerManager#6]
Warning: yaml_parse(): scanning error encountered during parsing: did not find expected alphabetic or numeric character (line 12, column 17), context while scanning an anchor (line 12, column 9) in phar://C:/Users/Family2/Desktop/Minecraft Things/Genysis/Genisys.phar/src/pocketmine/utils/Config.php on line 143

how to fix this

**Comment by Ad5001** [comment]
You seems to have made a yaml err

**Comment by AmiroEmad** [comment]
@Ad5001 yup ik but how to fix that error

**Comment by xBeastMode** [comment]
Don't use '§' in yaml :p

**Comment by AmiroEmad** [comment]
@xBeastMode thx alot didnt know that it was that simple lol
